[project]
name = "test-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "behave>=1.2.6",
    "retry>=0.9.2",
    "selenium>=4.27.1",
]
